%     RatSLAM script file for the ACRV_LAB_ROTATION dataset

%     Copyright (C) 2008 David Ball (d.ball@uq.edu.au) (MATLAB version)
%     Michael Milford (m.milford1@uq.edu.au) & Gordon Wyeth (g.wyeth@uq.edu.au)
% 
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
% 
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.

clear all;
%C:\RatSLAM-Dataset\log_irat_red.avi'
rs_main('C:\RatSLAM-Dataset\ACRV_lab_rotation.mp4', 0, 'st_lucia1_log', ...
    'IMAGE_X_OFFSET', 15, ...
    'BLOCK_READ', 100, ...
    'RENDER_RATE', 10, ...
    'VT_MATCH_THRESHOLD', 0.09, ...
    'IMAGE_VT_Y_RANGE', 30:280, ...
    'IMAGE_VT_X_RANGE', 200:1000, ...
    'IMAGE_VTRANS_Y_RANGE', 30:280, ...
    'IMAGE_VROT_Y_RANGE', 300:700, ...
    'IMAGE_ODO_X_RANGE', 200:1000, ...
    'EXP_DELTA_PC_THRESHOLD', 1.0, ...
    'EXP_CORRECTION', 0.5, ...
    'EXP_LOOPS', 100, ...
    'POSECELL_VTRANS_SCALING', 1/10);



